### ISSUE TITLE
Styles are not applying correctly on local development

### ISSUE THREAD

**Issue by braaar** [veltolini/website#22]
![Screenshot 2023-01-27 at 16 57 53](https://user-images.githubusercontent.com/5765650/215117102-b34bd1cb-a53d-4362-9d48-4496e996ad7c.jpg)

I tried deleting node_modules and reinstalling everything, but it seems the dev server somehow fails to apply the theme

**Comment by braaar** [comment]
`sx` styling works, but nothing in the theme applies.

**Comment by cobraz** [comment]
I do not have this issue btw.

**Comment by cobraz** [comment]
Seems like the built version of the website also works fine:
https://velt-website-chakra-14mz3ao7b-velt-as.vercel.app/

Have you tried deleting `.next`?

**Comment by braaar** [comment]
> Seems like the built version of the website also works fine: https://velt-website-chakra-14mz3ao7b-velt-as.vercel.app/
> 
> Have you tried deleting `.next`?

D'oh!
